# Link dotfiles/bash to ~/.bash

. ~/.bash/common/set_variable.sh

. ~/.bash/common/bashrc

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH=~/local/bin:/usr/local/root/bin:/usr/local/vim/bin:$PATH

export PETSC_DIR=/usr/local/petsc
export PETSC_ARCH_DEBUG=arch-linux-c-debug
export PETSC_ARCH_OPT=arch-linux-c-opt 
export SLEPC_DIR=/usr/local/slepc

. "$HOME/.deno/env"

# For VcXsrv
# Set wsl network to the mirroring mode
export DISPLAY=localhost:0.0
# export LIBGL_ALWAYS_INDIRECT=true
# export LIBGL_ALWAYS_SOFTWARE=true

eval $(~/local/bin/wsl2-ssh-agent)
