# Link dotfiles/bash to ~/.bash

# Remove Windows paths from PATH to improve completion speed
PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '^/mnt/c' | tr '\n' ':' | sed 's/:$//')

export PATH=~/local/bin:/usr/local/tmux/bin:/usr/local/neovim/bin:/usr/local/root/bin:/usr/local/vim/bin:$PATH

alias vim=nvim

. ~/.bash/common/bashrc

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PETSC_DIR=/usr/local/petsc
export PETSC_ARCH_DEBUG=arch-linux-c-debug
export PETSC_ARCH_OPT=arch-linux-c-opt 
export SLEPC_DIR=/usr/local/slepc

. "$HOME/.deno/env"

# For VcXsrv
# Set wsl network to the mirroring mode
export DISPLAY=localhost:0.0
# export LIBGL_ALWAYS_INDIRECT=true
# export LIBGL_ALWAYS_SOFTWARE=true

eval $(~/local/bin/wsl2-ssh-agent)

export NVM_DIR="$HOME/.nvm"
nvm_lazy_load() {
    unset -f nvm node npm npx
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    if [ -n "$1" ]; then
        "$@"
    fi
}

for cmd in nvm node npm npx; do
    eval "$cmd() { nvm_lazy_load $cmd \"\$@\"; }"
done
