# Link dotfiles/bash to ~/.bash

. ~/.bash/common/set_variable.sh

. ~/.bash/common/bashrc

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH=~/local/bin:/usr/local/root/bin:/usr/local/vim/bin:$PATH

. "$HOME/.deno/env"

# For VcXsrv
export DISPLAY=`hostname`.mshome.net:0.0
export LIBGL_ALWAYS_INDIRECT=true
export LIBGL_ALWAYS_SOFTWARE=true
