#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
fcitx5 &
systemctl --user start dunst
$HOME/.config/polybar/launch.sh

bspc monitor HDMI1 -d 4 5
bspc monitor HDMI2 -d 1 2 3
# bspc monitor rdp0 -d 1

bspc config top_padding     1 
bspc config bottom_padding  1 
bspc config left_padding    1
bspc config right_padding   1
bspc config border_width    2
bspc config window_gap      4
bspc config focused_border_color "#FFD700"
bspc config normal_border_color "#696969" 
bspc config active_border_color "#696969"

bspc config pointer_modifier "mod4"
bspc config pointer_action1 "move"
bspc config pointer_action2 "resize_side"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Inkscape state=floating follow=on
bspc rule -a ROOT state=floating follow=on

$HOME/.config/bspwm/watch_desktop_add_for_rename.sh &
