# Link dotfiles/bash to ~/.bash

export PATH=~/.node/gen/node_modules/.bin:/usr/local/neovim/bin:/usr/local/vim/bin:~/.local/bin:/home/kshu/.dotnet/tools:$PATH
. /usr/local/root/bin/thisroot.sh

alias vim=nvim

. ~/.bash/common/bashrc

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

. "$HOME/.deno/env"

# Auto-start ssh-agent
if [ -z "$SSH_AUTH_SOCK" ]; then
   eval $(ssh-agent -s) > /dev/null
fi
