unbind C-b
set -g prefix C-t
bind C-t send-prefix

set -g default-terminal "tmux-256color"

set -g mouse on
set -g history-limit 30000

bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-window-option -g mode-keys vi
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold] #I: #W #[default]"

set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY DBUS_SESSION_BUS_ADDRESS"

set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'

set-option -g set-titles on
set-option -g set-titles-string '#{pane_title}'
