[[plugins]]
repo="rebelot/kanagawa.nvim"


[[plugins]]
repo="nvim-treesitter/nvim-treesitter"

[[plugins]]
repo="nvim-treesitter/nvim-treesitter-context"


[[plugins]]
repo="neovim/nvim-lspconfig"

[[plugins]]
repo="ray-x/lsp_signature.nvim"


[[plugins]]
repo="mason-org/mason.nvim"
lua_source="require(\"mason\").setup()"
