# Necessary

[[plugins]]
repo="vim-denops/denops.vim"

[[plugins]]
repo="Shougo/dpp-protocol-git"
merge=false

[[plugins]]
repo="Shougo/dpp-ext-toml"
merge=false

[[plugins]]
repo="Shougo/dpp-ext-installer"
merge=false


# Edit support

# [[plugins]]
# repo="prabirshrestha/asyncomplete.vim"

# [[plugins]]
# repo="prabirshrestha/asyncomplete-lsp.vim"

[[plugins]]
repo="Shougo/ddc.vim"

[[plugins]]
repo="Shougo/ddc-ui-none"

[[plugins]]
repo="Shougo/ddc-ui-native"

[[plugins]]
repo="Shougo/ddc-source-around"

[[plugins]]
repo="Shougo/ddc-source-lsp"

[[plugins]]
repo="uga-rosa/ddc-source-vsnip"

[[plugins]]
repo="Shougo/ddc-matcher_head"

[[plugins]]
repo="Shougo/ddc-sorter_rank"

[[plugins]]
repo="hrsh7th/vim-vsnip"

[[plugins]]
repo="rafamadriz/friendly-snippets"
merged=false

[[plugins]]
repo="tyru/caw.vim"


# For skk

[[plugins]]
repo="vim-skk/skkeleton"


# For ddu

[[plugins]]
repo="Shougo/ddu.vim"

[[plugins]]
repo="Shougo/ddu-ui-ff"

[[plugins]]
repo="Shougo/ddu-ui-filer"

[[plugins]]
repo="Shougo/ddu-source-action"

[[plugins]]
repo="Shougo/ddu-source-file"

[[plugins]]
repo="Shougo/ddu-source-file_rec"

[[plugins]]
repo="uga-rosa/ddu-source-lsp"

[[plugins]]
repo="Shougo/ddu-column-filename"

[[plugins]]
repo="Shougo/ddu-kind-file"

[[plugins]]
repo="Shougo/ddu-filter-matcher_substring"


# LSP

[[plugins]]
repo="prabirshrestha/vim-lsp"

[[plugins]]
repo="mattn/vim-lsp-settings"


# TEX

[[plugins]]
repo="lervag/vimtex"


# C++

[[plugins]]
repo="kenji0923/cern_root.vim"

# [[plugins]]
# repo="ilyachur/cmake4vim"


# Others

# [[plugins]]
# repo="tpope/vim-dispatch"
