# Necessary

[[plugins]]
repo="vim-denops/denops.vim"

[[plugins]]
repo="Shougo/dpp-protocol-git"
merge=false

[[plugins]]
repo="Shougo/dpp-ext-toml"
merge=false

[[plugins]]
repo="Shougo/dpp-ext-lazy"
merge=false

[[plugins]]
repo="Shougo/dpp-ext-installer"
merge=false


# Edit support

[[plugins]]
repo="Shougo/ddc.vim"

[[plugins]]
repo="Shougo/ddc-ui-none"

[[plugins]]
repo="Shougo/ddc-ui-native"

[[plugins]]
repo="Shougo/ddc-ui-pum"

[[plugins]]
repo="Shougo/ddc-source-around"

[[plugins]]
repo="Shougo/ddc-source-lsp"

[[plugins]]
repo="uga-rosa/ddc-source-buffer"

[[plugins]]
repo="uga-rosa/ddc-source-vsnip"

[[plugins]]
repo="LumaKernel/ddc-source-file"

[[plugins]]
repo="Shougo/ddc-source-cmdline"

[[plugins]]
repo="Shougo/ddc-source-cmdline_history"

[[plugins]]
repo="Shougo/ddc-source-rg"

[[plugins]]
repo="Shougo/ddc-source-input"

[[plugins]]
repo="Shougo/ddc-source-line"

[[plugins]]
repo="Shougo/ddc-matcher_head"

[[plugins]]
repo="Shougo/ddc-sorter_rank"

[[plugins]]
repo="tani/ddc-fuzzy"

[[plugins]]
repo="hrsh7th/vim-vsnip"

[[plugins]]
repo="rafamadriz/friendly-snippets"
merged=false

[[plugins]]
repo="Shougo/pum.vim"

[[plugins]]
repo="machakann/vim-sandwich"


# For skk

[[plugins]]
repo="vim-skk/skkeleton"


# For ddu

[[plugins]]
repo="Shougo/ddu.vim"

[[plugins]]
repo="Shougo/ddu-ui-ff"

[[plugins]]
repo="Shougo/ddu-ui-filer"

[[plugins]]
repo="Shougo/ddu-source-action"

[[plugins]]
repo="Shougo/ddu-source-file"

[[plugins]]
repo="Shougo/ddu-source-file_rec"

[[plugins]]
repo="kenji0923/ddu-source-lsp"

[[plugins]]
repo="Shougo/ddu-column-filename"

[[plugins]]
repo="Shougo/ddu-kind-file"

[[plugins]]
repo="Shougo/ddu-filter-matcher_substring"

[[plugins]]
repo="uga-rosa/ddu-filter-converter_devicon"


# UI

[[plugins]]
repo="Shougo/cmdline.vim"


# Git

[[plugins]]
repo="lambdalisue/vim-gin"


# # LSP
#
# [[plugins]]
# repo="prabirshrestha/vim-lsp"
#
# [[plugins]]
# repo="kenji0923/vim-lsp-settings"
